model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 16
    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 16
        out_channels: 16
        model_channels: 224
        attention_resolutions: [8, 4, 2]
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        num_res_blocks: 2
        channel_mult: [1, 2, 3, 4]
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: logs/2023-12-11T21-44-32_autoencoder_kl_16x16x16_intergrowth/checkpoints/last.ckpt
        embed_dim: 16
        ddconfig:
          double_z: True
          z_channels: 16
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ 16 ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.intergrowth.IntergrowthDatasetTrain
      params:
        json_file: "/home/lina3782/labs/explain/intergrowth/data/metadata_shuffled.json"
        prefix: "/home/lina3782/data00/intergrowth/256/"
        size: 256
    validation:
      target: ldm.data.intergrowth.IntergrowthDatasetVal
      params:
        json_file: "/home/lina3782/labs/explain/intergrowth/data/metadata_shuffled.json"
        prefix: "/home/lina3782/data00/intergrowth/256/"
        size: 256


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True